import * as Y from 'yjs';
import type {SceneObject,Page} from './types';
export type {SceneObject,Page} from './types';
export const SCHEMA_VERSION=1;
export const uid=()=>crypto.randomUUID();
export function bytesToBase64(bytes:Uint8Array):string{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)}
export function base64ToBytes(value:string):Uint8Array{return Uint8Array.from(atob(value),c=>c.charCodeAt(0))}
export function objectsFromDoc(doc:Y.Doc):SceneObject[]{return Array.from(doc.getMap<Y.Map<any>>('objects').values()).filter(v=>v instanceof Y.Map).map(v=>v.toJSON() as SceneObject).sort((a,b)=>(a.order||0)-(b.order||0))}
export function pagesFromDoc(doc:Y.Doc):Page[]{return Array.from(doc.getMap<Y.Map<any>>('pages').values()).filter(v=>v instanceof Y.Map).map(v=>v.toJSON() as Page).sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id))}
export function createObject(doc:Y.Doc,values:Partial<SceneObject>):string{
 const id=values.id||uid();const type=values.type||'sticky';const o:Y.Map<any>=new Y.Map();
 const defaults:SceneObject={id,type,pageId:values.pageId||pagesFromDoc(doc)[0]?.id||newPage(doc),x:0,y:0,width:200,height:180,rotation:0,fill:type==='sticky'?'#fff2a8':'#e7e1ff',stroke:type==='sticky'?'transparent':'#65538e',strokeWidth:1,text:'',fontSize:22,bold:false,italic:false,align:'center',locked:false,opacity:1,order:doc.getMap('objects').size,...values};
 Object.entries(defaults).forEach(([k,v])=>{if(v!==undefined)o.set(k,k==='text'?new Y.Text(String(v)):v)});doc.getMap('objects').set(id,o);return id;
}
export function patchObject(doc:Y.Doc,id:string,patch:Partial<SceneObject>){const o=doc.getMap<Y.Map<any>>('objects').get(id);if(!o)return;for(const [k,v]of Object.entries(patch)){if(k==='id')continue;if(v===undefined){o.delete(k);continue}if(k==='text')changeText(doc,id,String(v));else o.set(k,v)}}
export function changeText(doc:Y.Doc,id:string,value:string){const o=doc.getMap<Y.Map<any>>('objects').get(id);if(!o)return;let text=o.get('text');if(!(text instanceof Y.Text)){text=new Y.Text();o.set('text',text)}const old=text.toString();let start=0;while(start<old.length&&start<value.length&&old[start]===value[start])start++;let end=0;while(end<old.length-start&&end<value.length-start&&old[old.length-1-end]===value[value.length-1-end])end++;if(old.length-start-end)text.delete(start,old.length-start-end);if(value.length-start-end)text.insert(start,value.slice(start,value.length-end));}
export function removeObjects(doc:Y.Doc,ids:string[]){const objects=objectsFromDoc(doc);for(const o of objects){if(ids.includes(o.id))continue;const patch:Partial<SceneObject>={};if(o.fromId&&ids.includes(o.fromId)){const target=objects.find(t=>t.id===o.fromId);patch.fromId='';patch.fromX=(target?.x||0)+(target?.width||0)/2;patch.fromY=(target?.y||0)+(target?.height||0)/2}if(o.toId&&ids.includes(o.toId)){const target=objects.find(t=>t.id===o.toId);patch.toId='';patch.toX=(target?.x||0)+(target?.width||0)/2;patch.toY=(target?.y||0)+(target?.height||0)/2}if(o.sectionId&&ids.includes(o.sectionId))patch.sectionId='';if(o.groupId&&ids.includes(o.groupId))patch.groupId='';patchObject(doc,o.id,patch)}ids.forEach(id=>doc.getMap('objects').delete(id));}
export function duplicateObjects(doc:Y.Doc,ids:string[],offset=30,targetPage?:string):string[]{const originals=objectsFromDoc(doc).filter(o=>ids.includes(o.id));const remap=new Map<string,string>();for(const o of originals){remap.set(o.id,uid());if(o.groupId&&!remap.has(o.groupId))remap.set(o.groupId,uid())}return originals.map(o=>createObject(doc,{...o,id:remap.get(o.id),pageId:targetPage||o.pageId,x:o.x+offset,y:o.y+offset,groupId:o.groupId?remap.get(o.groupId):undefined,sectionId:o.sectionId?remap.get(o.sectionId):undefined,fromId:o.fromId?(remap.get(o.fromId)||o.fromId):undefined,toId:o.toId?(remap.get(o.toId)||o.toId):undefined}));}
export function newPage(doc:Y.Doc,name='Page 1'):string{const id=uid(),p=new Y.Map();p.set('id',id);p.set('name',name);p.set('order',doc.getMap('pages').size);doc.getMap('pages').set(id,p);return id}
export function clonePage(doc:Y.Doc,id:string):string{const p=pagesFromDoc(doc).find(p=>p.id===id);const target=newPage(doc,`${p?.name||'Page'} copy`);duplicateObjects(doc,objectsFromDoc(doc).filter(o=>o.pageId===id).map(o=>o.id),0,target);return target}
export function deletePage(doc:Y.Doc,id:string){if(pagesFromDoc(doc).length<=1)return;removeObjects(doc,objectsFromDoc(doc).filter(o=>o.pageId===id).map(o=>o.id));doc.getMap('pages').delete(id)}
export function makeTemplate(name='blank'):Y.Doc{
 const doc=new Y.Doc();doc.transact(()=>{doc.getMap('meta').set('schemaVersion',SCHEMA_VERSION);const p=newPage(doc,'Page 1');const add=(v:Partial<SceneObject>)=>createObject(doc,{pageId:p,...v});
 const title=(text:string)=>add({type:'text',x:80,y:40,width:1100,height:70,text,fontSize:40,bold:true,fill:'transparent',stroke:'transparent',align:'left'});
 const section=(text:string,x:number,y:number,fill:string,width=320,height=470)=>add({type:'section',x,y,width,height,text,fill,stroke:fill,fontSize:21,align:'left'});
 const sticky=(text:string,x:number,y:number,fill='#fff2a8',sectionId?:string)=>add({type:'sticky',x,y,width:220,height:180,text,fill,sectionId,fontSize:20});
 const link=(fromId:string,toId:string,text='')=>add({type:'connector',fromId,toId,x:0,y:0,width:0,height:0,text,stroke:'#817596',routing:'elbow',arrowEnd:true,fill:'none',fontSize:16});
 if(name==='blank')return;
 if(name==='flowchart'){title('Map the path forward');const a=add({type:'rounded',x:100,y:210,width:180,height:100,text:'Start',fill:'#d7f5e5'}),b=add({type:'rectangle',x:380,y:210,width:220,height:100,text:'Explore the idea'}),c=add({type:'diamond',x:720,y:180,width:200,height:160,text:'Ready to go?',fill:'#fff2a8'}),d=add({type:'rounded',x:1050,y:210,width:180,height:100,text:'Launch',fill:'#d7f5e5'});link(a,b);link(b,c);link(c,d,'Yes');return}
 if(name==='mindmap'){title('Make room for possibility');const root=add({type:'rounded',x:450,y:350,width:240,height:120,text:'The big idea',fill:'#d8ceff',fontSize:27,bold:true});['People','Process','Possibilities','Next steps'].forEach((t,i)=>{const id=add({type:'rounded',x:i<2?80:900,y:180+(i%2)*340,width:220,height:100,text:t,fill:['#d7f5e5','#ffdfcc','#fff2a8','#d8eeff'][i]});link(root,id)});return}
 const labels:Record<string,string[]>={brainstorming:['How might we…','Ideas worth exploring','Let’s make it happen'],retrospective:['What went well','What could be better','What we’ll try next'],kanban:['To do','In progress','Done'],journey:['Discover','Consider','Experience','Return'],team:['Purpose','Desired outcomes','Stakeholders','Roles','Key deliverables','Core components','Ways of working']};
 const headers=labels[name]||labels.brainstorming;const titles:Record<string,string>={brainstorming:'A little space. A lot of ideas.',retrospective:'Look back. Move forward.',kanban:'From possibility to done.',journey:'Walk in your customer’s shoes.',team:'One team. A shared direction.'};title(titles[name]||titles.brainstorming);
 const colors=['#eee8ff','#e4f4ec','#fff1d8','#e4eeff'];headers.forEach((t,i)=>{const x=80+(i%4)*355,y=155+Math.floor(i/4)*520;const s=section(t,x,y,colors[i%4]);sticky(name==='brainstorming'?['What would make this easier for our customers?','Small ideas can lead to big things.','Choose one idea to test this week.'][i]:`Add your ${t.toLowerCase()} here`,x+45,y+75,['#fff2a8','#d4ebff','#ffd8df','#dfd5ff'][i%4],s);if(name==='brainstorming'&&i===0)sticky('Start with curiosity.\nEveryone has a voice.',x+45,y+270,'#ffd8df',s)});
 });return doc;
}
