import {test,expect,type BrowserContext,type Page} from '@playwright/test';
import * as Y from 'yjs';
import {makeTemplate,bytesToBase64} from '../../src/lib/model';
async function api(c:BrowserContext,action:string,data:Record<string,unknown>={}){const r=await c.request.post('/api',{data:{action,...data}});const b=await r.json();expect(r.ok(),`${action}: ${JSON.stringify(b)}`).toBeTruthy();return b}
async function account(c:BrowserContext,name:string){const email=`qa-browser-${crypto.randomUUID()}@canvaslab.test`;await api(c,'auth.register',{email,password:crypto.randomUUID(),name});return email}
async function ready(p:Page,id:string){await p.goto(`/board/${id}`);await expect(p.getByText('All changes saved')).toBeVisible({timeout:60000})}
async function createSticky(p:Page,text:string,x:number,y:number){await p.keyboard.press('s');await p.mouse.click(x,y);await p.getByLabel('Edit object text').fill(text);await p.keyboard.press('Escape');await expect(p.getByText('All changes saved')).toBeVisible({timeout:30000})}
test('two real browser contexts: collaboration, local undo, offline reconciliation and access revocation',async({browser})=>{
 test.setTimeout(180000);const a=await browser.newContext({baseURL:process.env.BASE_URL||'http://localhost:3000',viewport:{width:1440,height:900}}),b=await browser.newContext({baseURL:process.env.BASE_URL||'http://localhost:3000',viewport:{width:1440,height:900}});const emailA=await account(a,'QA Browser A'),emailB=await account(b,'QA Browser B');expect(emailA).not.toBe(emailB);const data=await api(a,'dashboard');const board=(await api(a,'board.create',{project_id:data.projects[0].id,name:'QA Two collaborators'})).board;await api(a,'board.share_set',{board_id:board.id,email:emailB,role:'editor'});
 const pa=await a.newPage(),pb=await b.newPage();const errors:string[]=[];pa.on('pageerror',e=>errors.push(e.message));pb.on('pageerror',e=>errors.push(e.message));await ready(pa,board.id);await ready(pb,board.id);
 await createSticky(pa,'Idea from A',400,300);await expect(pb.getByText('Idea from A',{exact:true})).toBeVisible();
 await createSticky(pb,'Idea from B',850,450);await expect(pa.getByText('Idea from B',{exact:true})).toBeVisible();
 await pa.keyboard.press('Meta+z');await expect(pa.getByText('Idea from A',{exact:true})).toBeHidden();await expect(pa.getByText('Idea from B',{exact:true})).toBeVisible();await pa.keyboard.press('Meta+Shift+z');await expect(pa.getByText('Idea from A',{exact:true})).toBeVisible();
 await pa.mouse.move(500,430);await expect(pb.locator('.collaborator-avatars button')).toHaveAttribute('title','Follow QA Browser A');
 const sticky=pa.locator('[data-object-id]').filter({hasText:'Idea from A'}).first();const before=await sticky.getAttribute('transform');const box=await sticky.boundingBox();await pa.mouse.move(box!.x+30,box!.y+30);await pa.mouse.down();await pa.mouse.move(box!.x+130,box!.y+90,{steps:8});await pa.mouse.up();await expect(sticky).not.toHaveAttribute('transform',before!);await expect(pa.getByText('All changes saved')).toBeVisible();
 await a.setOffline(true);await expect(pa.locator('.save-status')).toContainText('Offline',{timeout:15000});await createStickyOffline(pa,'Offline idea',700,280);await expect(pb.getByText('Offline idea',{exact:true})).toBeHidden();await a.setOffline(false);await expect(pa.getByText('All changes saved')).toBeVisible({timeout:60000});await expect(pb.getByText('Offline idea',{exact:true})).toBeVisible();
 await pa.getByRole('button',{name:'Share',exact:true}).click();await expect(pa.getByRole('dialog')).toBeVisible();await expect(pa.getByText('QA Browser B',{exact:true})).toBeVisible();await pa.screenshot({path:'artifacts/share-dialog.png'});await pa.getByLabel('Close dialog').click();
 await api(a,'board.share_set',{board_id:board.id,email:emailB,role:null});await expect(pb.getByText('This board is no longer available')).toBeVisible({timeout:15000});await pa.screenshot({path:'artifacts/multiplayer-editor.png'});expect(errors).toEqual([]);await a.close();await b.close();
});
async function createStickyOffline(p:Page,text:string,x:number,y:number){await p.keyboard.press('s');await p.mouse.click(x,y);await p.getByLabel('Edit object text').fill(text);await p.keyboard.press('Escape')}
test('templates, real comments, image upload, freehand, pages and exports',async({browser})=>{
 test.setTimeout(180000);const c=await browser.newContext({baseURL:process.env.BASE_URL||'http://localhost:3000',viewport:{width:1440,height:900}});await account(c,'QA Visual Workshop');const data=await api(c,'dashboard'),project=data.projects[0];const board=(await api(c,'board.create',{project_id:project.id,name:'Workshop Digital Product · Example',initial_update:bytesToBase64(Y.encodeStateAsUpdate(makeTemplate('brainstorming')))})).board;
 for(const [template,name]of [['team','Team canvas · Example'],['journey','Customer journey · Example'],['flowchart','Business process · Example']])await api(c,'board.create',{project_id:project.id,name,initial_update:bytesToBase64(Y.encodeStateAsUpdate(makeTemplate(template)))});
 const p=await c.newPage();await p.goto('/');await expect(p.getByText('Gathering your ideas…')).toBeHidden();await expect(p.getByRole('button',{name:'Open Workshop Digital Product · Example'})).toBeVisible();await expect(p.locator('.d-preview-empty .d-spin')).toHaveCount(0);await p.screenshot({path:'artifacts/dashboard-workspace.png'});await p.getByRole('navigation',{name:'Projects',exact:true}).getByRole('button').first().click();await p.screenshot({path:'artifacts/project-boards.png'});await ready(p,board.id);await p.screenshot({path:'artifacts/sample-board.png'});
 await p.getByLabel('Comments',{exact:true}).click();await p.getByLabel('New comment').fill('Let’s test the first idea with the team.');await p.getByRole('button',{name:'Post comment'}).click();await expect(p.getByText('Let’s test the first idea with the team.',{exact:true})).toBeVisible();await p.screenshot({path:'artifacts/comments.png'});await p.getByRole('button',{name:'Resolve',exact:true}).click();await expect(p.getByText('Let’s test the first idea with the team.',{exact:true})).toBeHidden();await p.getByLabel('Resolved',{exact:true}).check();await p.getByRole('button',{name:'Reopen',exact:true}).click();await p.getByLabel('Close panel').click();
 const upload=p.locator('input[type=file][accept="image/png,image/jpeg,image/webp"]');await upload.setInputFiles({name:'example.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDCUAAAAASUVORK5CYII=','base64')});await expect(p.getByText('Image uploaded')).toBeVisible();await expect(p.getByText('All changes saved')).toBeVisible();await p.reload();await expect(p.locator('svg image')).toHaveCount(1);
 await p.keyboard.press('p');await p.mouse.move(450,700);await p.mouse.down();await p.mouse.move(500,720,{steps:6});await p.mouse.move(580,680,{steps:6});await p.mouse.up();await expect(p.getByText('All changes saved')).toBeVisible();
 await p.getByLabel('Pages and outline').click();await p.getByLabel('Add page',{exact:true}).click();await expect(p.locator('.page-row')).toHaveCount(2);await expect(p.getByLabel('Switch page')).toContainText('Page 2');await p.locator('.page-row').filter({hasText:'Page 2'}).hover();await p.getByLabel('Duplicate Page 2',{exact:true}).click();await expect(p.locator('.page-row')).toHaveCount(3);await p.locator('.page-row').filter({hasText:'Page 2 copy'}).hover();await p.getByLabel('Move Page 2 copy up',{exact:true}).click();await p.getByLabel('Close outline').click();
 // Export the populated first page through real UI controls.
 await p.getByLabel('Pages and outline').click();await p.locator('.page-row>button').filter({hasText:'Page 1'}).click();await p.getByLabel('Close outline').click();
 for(const [name,suffix]of [['SVG vector','.svg'],['PNG image','.png'],['Editable .canvaslab','.canvaslab']]){await p.getByLabel('Board menu').click();const download=p.waitForEvent('download');await p.getByRole('button',{name,exact:true}).click();const d=await download;expect(d.suggestedFilename()).toContain(suffix);await d.saveAs(`artifacts/qa-export${suffix}`)}
 await expect(p.getByText('All changes saved')).toBeVisible();await p.keyboard.press('v');await p.keyboard.press('Escape');await p.setViewportSize({width:1280,height:800});await p.keyboard.press('1');await p.waitForTimeout(350);await p.screenshot({path:'artifacts/editor-1280.png'});await p.setViewportSize({width:1024,height:768});await p.keyboard.press('1');await p.waitForTimeout(350);await p.screenshot({path:'artifacts/editor-tablet.png'});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await c.close();
});
