import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import * as Y from 'yjs';
import {makeTemplate,objectsFromDoc,pagesFromDoc,createObject,changeText,patchObject,bytesToBase64,base64ToBytes} from '../src/lib/model';
const base=process.env.BASE_URL||'http://localhost:3000';
type Client={cookie:string;email:string;id:string};
const checks:{name:string,status:string,ms:number}[]=[];
async function call(c:Client|null,action:string,data:Record<string,unknown>={},expected=200){const r=await fetch(`${base}/api`,{method:'POST',headers:{'Content-Type':'application/json',...(c?{Cookie:c.cookie}:{})},body:JSON.stringify({action,...data})});const body=await r.json();assert.equal(r.status,expected,`${action}: ${JSON.stringify(body)}`);return {body,cookie:r.headers.get('set-cookie')?.split(';')[0]||''}}
async function check(name:string,fn:()=>Promise<void>){const start=performance.now();try{await fn();checks.push({name,status:'Passed',ms:Math.round(performance.now()-start)});console.log(`PASS ${name}`)}catch(e){checks.push({name,status:'Failed',ms:Math.round(performance.now()-start)});await writeFile('artifacts/integration-results.json',JSON.stringify(checks,null,2));throw e}}
async function register(name:string):Promise<Client>{const email=`qa-${crypto.randomUUID()}@canvaslab.test`;const {body,cookie}=await call(null,'auth.register',{name,email,password:`QA-${crypto.randomUUID()}`});return {email,cookie,id:body.user.id}}
const owner=await register('QA API Owner'),editor=await register('QA API Editor'),stranger=await register('QA API Stranger');
const db=(await call(owner,'dashboard')).body,workspace=db.workspaces[0],project=db.projects[0];let other:any,board:any,copy:any,asset:any,snapshot:any,thread:any,link:any;let doc=makeTemplate('flowchart');
await check('Workspace → projects → independent boards; private search isolation',async()=>{other=(await call(owner,'project.create',{workspace_id:workspace.id,name:'QA destination',is_private:true})).body.project;board=(await call(owner,'board.create',{project_id:project.id,name:'QA integration',initial_update:bytesToBase64(Y.encodeStateAsUpdate(doc))})).body.board;await call(stranger,'board.get',{board_id:board.id},404);assert.equal((await call(stranger,'dashboard')).body.boards.length,0);assert.equal((await call(stranger,'dashboard')).body.projects.some((p:any)=>p.id===project.id),false)});
await check('Persistent scene, server verified author, reconnect merge',async()=>{const a=(await call(owner,'scene.load',{board_id:board.id})).body;doc=new Y.Doc();a.updates.forEach((u:string)=>Y.applyUpdate(doc,base64ToBytes(u)));const id=createObject(doc,{type:'sticky',pageId:pagesFromDoc(doc)[0].id,text:'Persistent text',author:'forged'});const result=(await call(owner,'scene.push',{board_id:board.id,update_id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(doc))})).body;Y.applyUpdate(doc,base64ToBytes(result.update));assert.equal(objectsFromDoc(doc).find(o=>o.id===id)?.author,'QA API Owner');const loaded=(await call(owner,'scene.load',{board_id:board.id})).body;const late=new Y.Doc();loaded.updates.forEach((u:string)=>Y.applyUpdate(late,base64ToBytes(u)));assert.equal(objectsFromDoc(late).find(o=>o.id===id)?.text,'Persistent text')});
await check('Viewer/commenter deny API writes; editor grant scoped to one board',async()=>{await call(owner,'board.share_set',{board_id:board.id,email:editor.email,role:'viewer'});await call(editor,'scene.push',{board_id:board.id,update_id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(doc))},403);await call(editor,'comment.create',{board_id:board.id,text:'Denied'},403);await call(owner,'board.share_set',{board_id:board.id,email:editor.email,role:'commenter'});await call(editor,'scene.push',{board_id:board.id,update_id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(doc))},403);assert.equal((await call(editor,'board.get',{board_id:board.id})).body.project,null);await call(owner,'board.share_set',{board_id:board.id,email:editor.email,role:'editor'});assert.ok((await call(editor,'dashboard')).body.shared.includes(board.id))});
await check('Concurrent Y.Text/style converge on server; private favorites and Recent',async()=>{const d2=new Y.Doc();Y.applyUpdate(d2,Y.encodeStateAsUpdate(doc));const id=objectsFromDoc(doc)[0].id;const vector=Y.encodeStateVector(doc);changeText(doc,id,'Owner text');patchObject(d2,id,{fill:'#ff0000'});await Promise.all([call(owner,'scene.push',{board_id:board.id,update_id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(doc,vector))}),call(editor,'scene.push',{board_id:board.id,update_id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(d2,vector))})]);const merged=new Y.Doc();(await call(owner,'scene.load',{board_id:board.id})).body.updates.forEach((u:string)=>Y.applyUpdate(merged,base64ToBytes(u)));assert.equal(objectsFromDoc(merged)[0].text,'Owner text');assert.equal(objectsFromDoc(merged)[0].fill,'#ff0000');doc=merged;await call(owner,'board.favorite',{board_id:board.id,value:true});await call(owner,'board.recent',{board_id:board.id});assert.ok((await call(owner,'dashboard')).body.favorites.includes(board.id));assert.equal((await call(editor,'dashboard')).body.favorites.includes(board.id),false)});
await check('Assets private, real type validation, persistent comments/replies/resolve',async()=>{const data='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDCUAAAAASUVORK5CYII=';asset=(await call(owner,'asset.create',{board_id:board.id,name:'QA.png',mime:'image/png',data})).body.asset;assert.equal((await call(editor,'asset.get',{board_id:board.id,asset_id:asset.id})).body.asset.data,data);await call(stranger,'asset.get',{board_id:board.id,asset_id:asset.id},404);await call(owner,'asset.create',{board_id:board.id,name:'fake.png',mime:'image/png',data:btoa('<script>invalid image</script>')},400);thread=(await call(editor,'comment.create',{board_id:board.id,text:'A useful comment',object_id:objectsFromDoc(doc)[0].id})).body.comment;await call(owner,'comment.reply',{board_id:board.id,thread_id:thread.id,text:'A useful reply'});await call(owner,'comment.resolve',{board_id:board.id,thread_id:thread.id,resolved:true});assert.equal((await call(editor,'comment.list',{board_id:board.id})).body.comments.find((c:any)=>c.id===thread.id).resolved,true);await call(owner,'comment.resolve',{board_id:board.id,thread_id:thread.id,resolved:false})});
await check('Move retains ID, data, comments, assets; confirms permission change',async()=>{await call(owner,'board.update',{board_id:board.id,project_id:other.id},409);const moved=(await call(owner,'board.update',{board_id:board.id,project_id:other.id,access_confirmed:true,name:'QA moved'})).body.board;assert.equal(moved.id,board.id);assert.equal(moved.project_id,other.id);assert.ok((await call(owner,'comment.list',{board_id:board.id})).body.comments.length===2);assert.ok((await call(owner,'asset.get',{board_id:board.id,asset_id:asset.id})).body.asset)});
await check('Duplicate remaps objects and connectors; snapshot restores independent board',async()=>{copy=(await call(owner,'board.duplicate',{board_id:board.id})).body.board;assert.notEqual(copy.id,board.id);const duplicated=new Y.Doc();(await call(owner,'scene.load',{board_id:copy.id})).body.updates.forEach((u:string)=>Y.applyUpdate(duplicated,base64ToBytes(u)));const objects=objectsFromDoc(duplicated),originals=objectsFromDoc(doc);assert.ok(objects.every(o=>!originals.some(a=>a.id===o.id)));assert.ok(objects.filter(o=>o.type==='connector').every(o=>objects.some(t=>t.id===o.fromId)&&objects.some(t=>t.id===o.toId)));snapshot=(await call(owner,'snapshot.create',{board_id:board.id,name:'QA checkpoint'})).body.snapshot;const restored=(await call(owner,'snapshot.restore',{board_id:board.id,snapshot_id:snapshot.id})).body.board;assert.notEqual(restored.id,board.id)});
await check('Link access default viewer, revoke link, owner session preserved',async()=>{link=(await call(owner,'board.link_create',{board_id:board.id})).body;assert.ok((await call(owner,'auth.me')).body.user);await call(stranger,'board.link_accept',{token:link.token});assert.equal((await call(stranger,'board.get',{board_id:board.id})).body.role,'viewer');await call(owner,'board.link_revoke',{board_id:board.id,link_id:link.link.id});await call(stranger,'board.get',{board_id:board.id},404)});
await check('Shared timer transitions, facilitator enforcement, vote privacy and quota',async()=>{await call(owner,'workshop.timer',{board_id:board.id,operation:'start',duration_ms:60000});await call(editor,'workshop.timer',{board_id:board.id,operation:'pause'},403);await call(owner,'workshop.timer',{board_id:board.id,operation:'pause'});assert.equal((await call(editor,'workshop.get',{board_id:board.id})).body.timer.state,'paused');await call(owner,'workshop.timer',{board_id:board.id,operation:'resume'});await call(owner,'workshop.timer',{board_id:board.id,operation:'reset'});const ids=objectsFromDoc(doc).filter(o=>o.type!=='connector').map(o=>o.id);await call(owner,'workshop.vote_start',{board_id:board.id,title:'QA Vote',eligible:ids,quota:1});await call(owner,'workshop.vote_cast',{board_id:board.id,object_id:ids[0]});const privateView=(await call(editor,'workshop.get',{board_id:board.id})).body;assert.equal(privateView.privateVoting,true);assert.equal(privateView.vote.results,null);assert.equal(privateView.vote.mine.length,0);await call(owner,'workshop.vote_cast',{board_id:board.id,object_id:ids[1]},409);await call(editor,'workshop.vote_end',{board_id:board.id},403);await call(editor,'workshop.vote_cast',{board_id:board.id,object_id:ids[0]});await call(owner,'workshop.vote_end',{board_id:board.id});assert.equal((await call(editor,'workshop.get',{board_id:board.id})).body.vote.results[0].count,2)});
await check('Editable export/import remaps references and rejects corrupt bundle',async()=>{const bundle=(await call(owner,'board.export',{board_id:board.id})).body;assert.equal(bundle.schemaVersion,1);assert.equal(bundle.assets.length,1);const imported=(await call(owner,'board.import',{project_id:project.id,bundle})).body.board;const content=(await call(owner,'board.export',{board_id:imported.id})).body;assert.equal(content.objects.length,bundle.objects.length);assert.notEqual(content.objects[0].id,bundle.objects[0].id);await call(owner,'board.import',{project_id:project.id,bundle:{schemaVersion:999}},400)});
await check('Trash project restores only its batch; revoked access blocks future writes',async()=>{await call(owner,'board.trash',{board_id:copy.id});await call(owner,'project.trash',{project_id:other.id});await call(editor,'board.get',{board_id:board.id},404);await call(owner,'project.restore',{project_id:other.id});await call(owner,'board.get',{board_id:board.id});await call(owner,'board.get',{board_id:copy.id},404);await call(owner,'board.restore',{board_id:copy.id});await call(owner,'board.share_set',{board_id:board.id,email:editor.email,role:null});await call(editor,'scene.push',{board_id:board.id,update_id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(doc))},404)});
await writeFile('artifacts/integration-results.json',JSON.stringify(checks,null,2));console.log(`${checks.length} integration scenarios passed against real Supabase`);
