import {describe,it,expect} from 'vitest';
import * as Y from 'yjs';
import {makeTemplate,objectsFromDoc,pagesFromDoc,createObject,changeText,patchObject,removeObjects,duplicateObjects,deletePage,clonePage} from '../src/lib/model';
describe('collaborative scene model',()=>{
 it('starts every blank board with a page',()=>{const d=makeTemplate();expect(pagesFromDoc(d)).toHaveLength(1);expect(objectsFromDoc(d)).toHaveLength(0)});
 it.each(['brainstorming','retrospective','kanban','flowchart','mindmap','journey','team'])('creates independent editable %s templates',name=>{const a=makeTemplate(name),b=makeTemplate(name);expect(objectsFromDoc(a).length).toBeGreaterThan(3);expect(objectsFromDoc(a)[0].id).not.toBe(objectsFromDoc(b)[0].id);changeText(a,objectsFromDoc(a)[0].id,'Changed');expect(objectsFromDoc(b)[0].text).not.toBe('Changed')});
 it('merges concurrent text and style changes without overwriting either',()=>{const a=makeTemplate();const id=createObject(a,{text:'Hello'}),b=new Y.Doc();Y.applyUpdate(b,Y.encodeStateAsUpdate(a));const va=Y.encodeStateVector(a),vb=Y.encodeStateVector(b);changeText(a,id,'Hello world');patchObject(b,id,{fill:'#ff0000',x:340});Y.applyUpdate(a,Y.encodeStateAsUpdate(b,va));Y.applyUpdate(b,Y.encodeStateAsUpdate(a,vb));expect(objectsFromDoc(a)).toEqual(objectsFromDoc(b));expect(objectsFromDoc(a)[0]).toMatchObject({text:'Hello world',fill:'#ff0000',x:340})});
 it('undo only reverts this user’s action',()=>{const a=makeTemplate(),id=createObject(a,{text:'Keep me'}),b=new Y.Doc();Y.applyUpdate(b,Y.encodeStateAsUpdate(a));const origin={};const undo=new Y.UndoManager(a.getMap('objects'),{trackedOrigins:new Set([origin])});a.transact(()=>patchObject(a,id,{x:200}),origin);patchObject(b,id,{fill:'#123456'});Y.applyUpdate(a,Y.encodeStateAsUpdate(b),'remote');undo.undo();expect(objectsFromDoc(a)[0]).toMatchObject({x:0,fill:'#123456',text:'Keep me'})});
 it('remaps duplicated connector binding and group identities',()=>{const d=makeTemplate(),a=createObject(d,{groupId:'group-one'}),b=createObject(d,{x:400,groupId:'group-one'}),c=createObject(d,{type:'connector',fromId:a,toId:b});const ids=duplicateObjects(d,[a,b,c]);const clone=objectsFromDoc(d).filter(o=>ids.includes(o.id));expect(clone[2].fromId).toBe(clone[0].id);expect(clone[2].toId).toBe(clone[1].id);expect(clone[0].groupId).not.toBe('group-one');expect(clone[0].groupId).toBe(clone[1].groupId)});
 it('detaches connectors on delete and preserves final page',()=>{const d=makeTemplate(),a=createObject(d,{x:150,y:60}),c=createObject(d,{type:'connector',fromId:a});removeObjects(d,[a]);expect(objectsFromDoc(d).find(o=>o.id===c)?.fromId).toBe('');deletePage(d,pagesFromDoc(d)[0].id);expect(pagesFromDoc(d)).toHaveLength(1)});
 it('duplicates a page with independent ids and content',()=>{const d=makeTemplate('flowchart'),old=pagesFromDoc(d)[0].id,newId=clonePage(d,old);expect(newId).not.toBe(old);const oldObjects=objectsFromDoc(d).filter(o=>o.pageId===old),copy=objectsFromDoc(d).filter(o=>o.pageId===newId);expect(copy.length).toBe(oldObjects.length);const conn=copy.find(o=>o.type==='connector')!;expect(copy.some(o=>o.id===conn.fromId)).toBe(true)});
});
