import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import WebSocket from 'ws';
import * as Y from 'yjs';
import {createObject,bytesToBase64,base64ToBytes,pagesFromDoc} from '../src/lib/model';
const url=process.env.BASE_URL||'http://localhost:3000';const results:string[]=[];
async function api(cookie:string,action:string,data:Record<string,unknown>={}){const r=await fetch(`${url}/api`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({action,...data})});const body=await r.json();assert.equal(r.status,200,`${action}: ${JSON.stringify(body)}`);return {body,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie}}
async function user(name:string){const email=`qa-ws-${crypto.randomUUID()}@canvaslab.test`;return {...await api('','auth.register',{email,password:crypto.randomUUID(),name}),email}}
class Peer{ws:WebSocket;messages:any[]=[];closed:number|undefined;constructor(cookie:string,board:string,origin=url){this.ws=new WebSocket(`${url.replace('http','ws')}/sync?board=${board}`,{headers:{Cookie:cookie,Origin:origin}});this.ws.on('message',m=>this.messages.push(JSON.parse(m.toString())));this.ws.on('close',code=>{this.closed=code});}async wait(predicate:(m:any)=>boolean,timeout=20000){const start=Date.now();while(Date.now()-start<timeout){const i=this.messages.findIndex(predicate);if(i>=0)return this.messages.splice(i,1)[0];await new Promise(r=>setTimeout(r,30))}throw Error('WebSocket response timeout')}async closeCode(){const start=Date.now();while(!this.closed&&Date.now()-start<20000)await new Promise(r=>setTimeout(r,30));return this.closed}}
const owner=await user('QA Socket Owner'),guest=await user('QA Socket Guest');const dashboard=(await api(owner.cookie,'dashboard')).body;const board=(await api(owner.cookie,'board.create',{project_id:dashboard.projects[0].id,name:'QA socket checks'})).body.board;
await api(owner.cookie,'board.share_set',{board_id:board.id,email:guest.email,role:'viewer'});const viewer=new Peer(guest.cookie,board.id);const initial=await viewer.wait(m=>m.type==='init');const doc=new Y.Doc();Y.applyUpdate(doc,base64ToBytes(initial.update));createObject(doc,{pageId:pagesFromDoc(doc)[0].id,text:'Forbidden edit'});viewer.ws.send(JSON.stringify({type:'update',id:crypto.randomUUID(),update:bytesToBase64(Y.encodeStateAsUpdate(doc))}));assert.equal((await viewer.wait(m=>m.type==='error')).status,403);assert.equal(await viewer.closeCode(),4403);results.push('Viewer cannot write through a direct WebSocket message');
await api(owner.cookie,'board.share_set',{board_id:board.id,email:guest.email,role:'editor'});const pa=new Peer(owner.cookie,board.id),pb=new Peer(guest.cookie,board.id);await pa.wait(m=>m.type==='init');await pb.wait(m=>m.type==='init');pb.ws.send(JSON.stringify({type:'presence',value:{x:123,y:456,pageId:pagesFromDoc(doc)[0].id,user:{id:owner.body.user.id,name:'Forged owner'},chat:{text:'Hello',at:0}}}));const presence=await pa.wait(m=>m.type==='presence'&&m.x===123);assert.equal(presence.user.id,guest.body.user.id);assert.equal(presence.user.name,'QA Socket Guest');assert.notEqual(presence.chat.at,0);results.push('Presence identity and message timestamps are server authoritative');
await api(owner.cookie,'board.share_set',{board_id:board.id,email:guest.email,role:null});assert.equal(await pb.closeCode(),4403);results.push('Revocation closes an active editor socket');
const badOrigin=new Peer(owner.cookie,board.id,'https://attacker.invalid');assert.equal(await badOrigin.closeCode(),4403);results.push('Cross-origin WebSocket upgrade is rejected');
await api(owner.cookie,'board.trash',{board_id:board.id});assert.equal(await pa.closeCode(),4403);results.push('Trash closes an active owner socket');
await api(owner.cookie,'board.restore',{board_id:board.id});await writeFile('artifacts/ws-security.json',JSON.stringify(results.map(name=>({name,status:'Passed'})),null,2));console.log(results.map(x=>'PASS '+x).join('\n'));
