import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { ArrowDownAZ, ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronRight, Clock3, Copy, Ellipsis, File, FolderKanban, Grid2X2, Home, LayoutTemplate, List, LoaderCircle, LockKeyhole, LogOut, MoveRight, Pencil, Plus, Search, Settings2, Sparkles, Star, Trash2, Undo2, Upload, Users, X } from 'lucide-react';
import * as Y from 'yjs';
import { api } from '../lib/api';
import { bytesToBase64, makeTemplate } from '../lib/model';
import type { Board, Project, Role, User, Workspace } from '../lib/types';
import Modal from '../components/Modal';
import { BoardPreview, TemplatePreview, templates } from './Preview';
import './dashboard.css';

type View = 'home' | 'recent' | 'favorites' | 'projects' | 'shared' | 'trash';
interface DashboardData { workspaces: Workspace[]; projects: Project[]; boards: Board[]; favorites: string[]; recents: string[]; shared?:string[] }
type Dialog = { kind: 'create-board'; template: string } | { kind: 'project'; project?: Project } | { kind: 'workspace'; workspace?: Workspace } | { kind: 'rename'; board: Board } | { kind: 'move'; board: Board; destination?: string } | { kind: 'trash-board'; board: Board } | { kind: 'trash-project'; project: Project } | { kind: 'members'; entity: 'workspace' | 'project'; id: string; name: string; role: Role } | { kind: 'templates' } | { kind: 'restore-board'; board: Board };
interface EditableBundle { schemaVersion: number; board?: { name?: string }; pages: unknown[]; objects: unknown[]; assets: unknown[] }
interface Member { id?: string; user_id?: string; name?: string; email?: string; role: Role; color?: string; user?: User }
const emptyData: DashboardData = { workspaces: [], projects: [], boards: [], favorites: [], recents: [] };
const projectColors = ['#8570cc', '#68a58c', '#e6ad61', '#da8a9c', '#669abd', '#868c9e'];
const projectIcons = ['✳', '◈', '◉', '✦', '⚑', '↗', '☀', '◎'];
const editable = (role?: Role) => role === 'owner' || role === 'editor';
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong. Please try again.';
function relativeTime(date: string) { const seconds = Math.max(0, (Date.now()-new Date(date).getTime())/1000); if(!Number.isFinite(seconds)) return 'Recently'; if(seconds<60)return 'Just now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;if(seconds<604800)return `${Math.floor(seconds/86400)}d ago`;return new Date(date).toLocaleDateString(undefined,{month:'short',day:'numeric'}); }
function avatarLetters(name: string) { return name.trim().split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase() || 'U'; }

export default function Dashboard({ user, onOpenBoard, onLogout }: { user: User; onOpenBoard: (id: string) => void; onLogout: () => void }) {
  const importInput=useRef<HTMLInputElement>(null);const [importBundle,setImportBundle]=useState<EditableBundle>();
  const [data, setData] = useState<DashboardData>(emptyData);
  const [workspaceId, setWorkspaceId] = useState('');
  const [view, setView] = useState<View>('home');
  const [projectId, setProjectId] = useState('');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('updated');
  const [layout, setLayout] = useState<'grid'|'list'>('grid');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [menu, setMenu] = useState('');
  const [dialog, setDialog] = useState<Dialog | null>(null);
  const [dragTarget, setDragTarget] = useState('');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const reload = useCallback(async (quiet = false) => {
    try { const next = await api<DashboardData>('dashboard'); setData(next); setWorkspaceId(current => next.workspaces.some(w=>w.id===current) ? current : next.workspaces[0]?.id || ''); setError(''); }
    catch(cause) { if(!quiet) setError(errorText(cause)); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void reload(); const refresh = () => { void reload(true); }; window.addEventListener('canvaslab:metadata',refresh); const interval=window.setInterval(refresh,5000);return()=>{window.removeEventListener('canvaslab:metadata',refresh);window.clearInterval(interval);}; },[reload]);
  useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(''),4200);return()=>window.clearTimeout(timer)},[toast]);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(!(event.target as Element).closest('[data-menu], .d-context-menu'))setMenu('')};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu('');setSidebarOpen(false)}};document.addEventListener('click',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',escape)}},[]);
  useEffect(()=>{if(!loading&&projectId&&!data.projects.some(p=>p.id===projectId&&p.workspace_id===workspaceId&&!p.deleted_at)){setProjectId('');setView('home');setQuery('');}},[data.projects,projectId,workspaceId,loading]);
  const workspace = data.workspaces.find(w=>w.id===workspaceId);
  const projects = useMemo(()=>data.projects.filter(p=>p.workspace_id===workspaceId && !p.deleted_at),[data.projects,workspaceId]);
  const project = projects.find(p=>p.id===projectId);
  const destinations = projects.filter(p=>editable(p.role));
  const boardWorkspace = (board: Board) => board.workspace_id || data.projects.find(p=>p.id===board.project_id)?.workspace_id;
  const liveBoards = data.boards.filter(b=>!b.deleted_at && boardWorkspace(b)===workspaceId && !data.projects.find(p=>p.id===b.project_id)?.deleted_at);
  const favoriteSet = useMemo(()=>new Set(data.favorites),[data.favorites]);
  const visibleBoards = data.boards.filter(board=> {
    if(view==='trash'&&!projectId) return Boolean(board.deleted_at) && boardWorkspace(board)===workspaceId && !data.projects.find(p=>p.id===board.project_id)?.deleted_at && board.name.toLowerCase().includes(query.toLowerCase());
    if(board.deleted_at || data.projects.find(p=>p.id===board.project_id)?.deleted_at)return false;
    if(projectId && board.project_id!==projectId)return false;
    if(!projectId && view==='shared') { if(!(data.shared||[]).includes(board.id))return false; }
    else if(boardWorkspace(board)!==workspaceId)return false;
    if(!projectId && view==='favorites' && !favoriteSet.has(board.id))return false;
    if(!projectId && view==='recent' && !data.recents.includes(board.id))return false;
    return board.name.toLowerCase().includes(query.toLowerCase());
  }).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='created'?new Date(b.created_at).getTime()-new Date(a.created_at).getTime():new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime());
  const shownProjects = projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
  const trashedProjects = data.projects.filter(p=>p.workspace_id===workspaceId && p.deleted_at && p.name.toLowerCase().includes(query.toLowerCase()));
  const changeView=(next:View)=>{setView(next);setProjectId('');setQuery('');setSidebarOpen(false);setMenu('')};
  const openProject=(id:string)=>{setProjectId(id);setView('home');setQuery('');setSidebarOpen(false);setMenu('')};
  const openBoard=(id:string)=>{void api('board.recent',{board_id:id}).catch(()=>{});onOpenBoard(id)};
  const showDialog=(next:Dialog)=>{setMenu('');setError('');setDialog(next)};
  async function perform<T = unknown>(action:string,payload:Record<string,unknown>,message?:string):Promise<T|undefined> {
    setBusy(true);setError('');
    try {const result=await api<T>(action,payload);await reload(true);if(message)setToast(message);return result}
    catch(cause){setError(errorText(cause));return undefined}
    finally {setBusy(false)}
  }
  async function closeAfter(action:string,payload:Record<string,unknown>,message:string) {const result=await perform(action,payload,message);if(result!==undefined)setDialog(null)}
  const moveBoard=(board:Board,destination?:string)=>{if(destination===board.project_id)return;showDialog({kind:'move',board,destination})};
  const newBoard=(template='blank')=>{if(!destinations.length){if(editable(workspace?.role)){showDialog({kind:'project'});setToast('Create a project to give your board a home.')}else setError('You need edit access to a project to create a board.')}else showDialog({kind:'create-board',template})};
  const canMove=(board:Board)=>editable(data.projects.find(p=>p.id===board.project_id)?.role)&&destinations.some(p=>p.id!==board.project_id&&p.workspace_id===boardWorkspace(board));
  const duplicateBoard=(board:Board)=>{const destination=destinations.find(p=>p.id===board.project_id)||destinations[0];if(!destination)return;setMenu('');void perform('board.duplicate',{board_id:board.id,project_id:destination.id},`Independent copy created in ${destination.name}`)};
  const heading = project?.name || ({home:'A little space for big ideas.',recent:'Pick up where you left off.',favorites:'Your favorites, all together.',projects:'Every idea has a home.',shared:'Better when we work together.',trash:'A second chance for ideas.'} as const)[view];
  const description = project ? project.description || 'A shared space for the ideas, plans, and possibilities ahead.' : ({home:'Bring your thoughts together. Make something great with your team.',recent:'Jump back into the boards you’ve opened recently.',favorites:'The boards you want to keep close at hand.',projects:'Organize your boards around the things you’re working on.',shared:'Boards that people have shared directly with you.',trash:'Restore a project or board whenever you need it again.'} as const)[view];
  return <div className="d-shell">
    {sidebarOpen && <button className="d-sidebar-scrim" aria-label="Close navigation" onClick={()=>setSidebarOpen(false)} />}
    <aside className={`d-sidebar ${sidebarOpen?'d-sidebar-open':''}`}>
      <button className="d-brand" onClick={()=>changeView('home')} aria-label="CanvasLab home"><span className="d-brand-mark"><i/><i/><i/><i/></span>CanvasLab<span>.</span></button>
      <div className="d-workspace-wrap"><button className="d-workspace-switch" data-menu onClick={()=>setMenu(menu==='workspace'?'':'workspace')} aria-expanded={menu==='workspace'}><span className="d-workspace-avatar">{avatarLetters(workspace?.name||'Workspace')}</span><span className="d-workspace-label"><strong>{workspace?.name||'Your workspace'}</strong><small>Team workspace</small></span><ChevronDown size={14}/></button>
        {menu==='workspace' && <div className="d-context-menu d-workspace-menu"><span className="d-menu-label">YOUR WORKSPACES</span>{data.workspaces.map(w=><button key={w.id} onClick={()=>{setWorkspaceId(w.id);changeView('home')}}><span className="d-small-workspace">{avatarLetters(w.name)}</span><span>{w.name}</span>{w.id===workspaceId&&<Check size={14}/>}</button>)}<hr/><button onClick={()=>showDialog({kind:'workspace'})}><Plus size={15}/>Create workspace</button>{workspace?.role==='owner'&&<button onClick={()=>showDialog({kind:'workspace',workspace})}><Settings2 size={15}/>Workspace settings</button>}<button onClick={()=>workspace&&showDialog({kind:'members',entity:'workspace',id:workspace.id,name:workspace.name,role:workspace.role})}><Users size={15}/>Workspace members</button></div>}
      </div>
      <nav className="d-navigation" aria-label="Main navigation">{([{id:'home',icon:Home,label:'Home'},{id:'recent',icon:Clock3,label:'Recent'},{id:'favorites',icon:Star,label:'Favorites'}] as const).map(item=><button key={item.id} className={!projectId&&view===item.id?'active':''} onClick={()=>changeView(item.id)}><item.icon size={17}/>{item.label}{item.id==='favorites'&&liveBoards.filter(b=>favoriteSet.has(b.id)).length>0&&<span className="d-nav-count">{liveBoards.filter(b=>favoriteSet.has(b.id)).length}</span>}</button>)}</nav>
      <div className="d-project-heading"><button onClick={()=>changeView('projects')} className={view==='projects'?'selected':''}>Projects<ChevronRight size={12}/></button>{editable(workspace?.role)&&<button className="d-sidebar-add" title="New project" aria-label="New project" onClick={()=>showDialog({kind:'project'})}><Plus size={16}/></button>}</div>
      <nav className="d-project-nav" aria-label="Projects">{projects.map(p=><button key={p.id} onClick={()=>openProject(p.id)} onDragOver={e=>{if(editable(p.role)){e.preventDefault();setDragTarget(p.id)}}} onDragLeave={()=>setDragTarget('')} onDrop={e=>{e.preventDefault();setDragTarget('');const board=data.boards.find(b=>b.id===e.dataTransfer.getData('application/x-canvaslab-board'));if(board&&canMove(board)&&editable(p.role))moveBoard(board,p.id)}} className={`${p.id===projectId?'active':''} ${dragTarget===p.id?'d-drop-target':''}`}><span className="d-project-icon" style={{color:p.color||'#9482bc'}}>{p.icon||'✳'}</span><span>{p.name}</span>{p.is_private&&<LockKeyhole size={11} className="d-project-private"/>}</button>)}{!projects.length&&!loading&&<p className="d-sidebar-empty">A project is a home for your boards. Create your first one.</p>}</nav>
      <nav className="d-navigation d-secondary-nav" aria-label="More views"><button className={!projectId&&view==='shared'?'active':''} onClick={()=>changeView('shared')}><Users size={17}/>Shared with me</button><button className={!projectId&&view==='trash'?'active':''} onClick={()=>changeView('trash')}><Trash2 size={16}/>Trash</button></nav>
      <div className="d-sidebar-bottom"><div className="d-sidebar-note"><span>✳</span><strong>Good ideas grow here.</strong><p>A canvas for thinking out loud.</p></div><div className="d-user-wrap"><button className="d-user-button" data-menu onClick={()=>setMenu(menu==='user'?'':'user')}><span className="d-user-avatar" style={{background:user.color||'#dcc8ec'}}>{avatarLetters(user.name)}</span><span><strong>{user.name}</strong><small>{user.email}</small></span><ChevronDown size={13}/></button>{menu==='user'&&<div className="d-context-menu d-user-menu"><span className="d-menu-label">{user.email}</span><button onClick={()=>{setMenu('');onLogout()}}><LogOut size={15}/>Sign out</button></div>}</div></div>
    </aside>
    <main className="d-main">
      <header className="d-topbar"><button className="d-mobile-nav d-icon-button" aria-label="Open navigation" onClick={()=>setSidebarOpen(true)}><List size={20}/></button><div className="d-breadcrumb"><button onClick={()=>changeView('home')}>{workspace?.name||'Workspace'}</button><ChevronRight size={13}/><span>{project?.name||({home:'Home',recent:'Recent',favorites:'Favorites',projects:'Projects',shared:'Shared with me',trash:'Trash'} as const)[view]}</span></div><span className="d-topbar-right"><span className="d-team-indicator"><span/>Your team’s thinking space</span><span className="d-topbar-avatar" style={{background:user.color||'#e6d6ec'}} title={user.name}>{avatarLetters(user.name)}</span></span></header>
      <div className="d-content">
        {error&&!dialog&&<div className="d-error" role="alert"><span>{error}</span><button onClick={()=>void reload()}>Try again</button><button className="d-icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}
        <div className="d-page-heading"><div>{project&&<span className="d-project-badge" style={{background:`${project.color||'#8570cc'}15`,color:project.color||'#8570cc'}}>{project.icon||'✳'}</span>}<span className="d-page-eyebrow">{project?'PROJECT':view==='home'?`YOUR WORKSPACE, ${user.name.split(' ')[0].toUpperCase()}`:'YOUR WORKSPACE'}</span><h1>{heading}{project?.is_private&&<LockKeyhole size={17}/>}</h1><p>{description}</p>{project&&<div className="d-project-meta"><span><File size={12}/>{liveBoards.filter(b=>b.project_id===project.id).length} boards</span><span>{project.is_private?'Private project':'Workspace project'}</span><button onClick={()=>showDialog({kind:'members',entity:'project',id:project.id,name:project.name,role:project.role})}><Users size={12}/>Members & access</button></div>}</div><div className="d-page-heading-actions">{view!=='trash'&&destinations.length>0&&<button className="d-button" onClick={()=>importInput.current?.click()}><Upload size={15}/>Import board</button>}{project&&editable(project.role)&&<div className="d-relative"><button className="d-button d-button-square" aria-label="Project options" data-menu onClick={()=>setMenu(menu==='project'?'':'project')}><Ellipsis size={18}/></button>{menu==='project'&&<div className="d-context-menu d-menu-right"><button onClick={()=>showDialog({kind:'project',project})}><Pencil size={15}/>Edit project</button><button onClick={()=>showDialog({kind:'members',entity:'project',id:project.id,name:project.name,role:project.role})}><Users size={15}/>Members & access</button>{project.role==='owner'&&<><hr/><button className="d-danger" onClick={()=>showDialog({kind:'trash-project',project})}><Trash2 size={15}/>Move to Trash</button></>}</div>}</div>}{view==='projects'&&!projectId?<button className="d-button d-button-primary" disabled={!editable(workspace?.role)} onClick={()=>showDialog({kind:'project'})}><Plus size={16}/>New project</button>:view!=='trash'&&(!project||editable(project.role))&&<button className="d-button d-button-primary" onClick={()=>newBoard()}><Plus size={16}/>New board</button>}</div></div>
        {loading?<div className="d-loading"><LoaderCircle className="d-spin" size={26}/><p>Gathering your ideas…</p></div>:<>
          {!projectId&&view==='home'&&!query&&<section className="d-template-section"><div className="d-section-heading"><h2><Sparkles size={15}/>A starting point for something great</h2><button onClick={()=>showDialog({kind:'templates'})}>Explore templates<ArrowUpRight size={14}/></button></div><div className="d-template-strip">{templates.slice(0,5).map(template=><button className="d-template-card" key={template.id} onClick={()=>newBoard(template.id)}><div className="d-template-art" style={{background:template.color}}><TemplatePreview type={template.id}/></div><span><strong>{template.name}</strong><small>{template.tag}</small></span><ArrowUpRight size={13}/></button>)}</div></section>}
          <section className="d-boards-section"><div className="d-boards-heading"><h2>{project?'All boards':view==='projects'?'Your projects':view==='trash'?'In the trash':view==='home'?'Your boards':view==='recent'?'Recently opened':view==='favorites'?'Favorite boards':'Shared boards'}<span>{view==='projects'?shownProjects.length:view==='trash'?visibleBoards.length+trashedProjects.length:visibleBoards.length}</span></h2><div className="d-view-tools"><label className="d-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={project?'Search this project…':'Search boards and projects…'} aria-label={project?'Search this project':'Search boards and projects'}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={12}/></button>}</label><label className="d-sort"><ArrowDownAZ size={15}/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort boards"><option value="updated">Last updated</option><option value="created">Date created</option><option value="name">Name A–Z</option></select><ChevronDown size={12}/></label><div className="d-layout-toggle"><button className={layout==='grid'?'active':''} aria-label="Grid view" aria-pressed={layout==='grid'} onClick={()=>setLayout('grid')}><Grid2X2 size={16}/></button><button className={layout==='list'?'active':''} aria-label="List view" aria-pressed={layout==='list'} onClick={()=>setLayout('list')}><List size={17}/></button></div></div></div>
            {(view==='projects'||query&&!projectId)&&view!=='trash'&&shownProjects.length>0&&<div className="d-project-grid">{[...shownProjects].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):0).map(p=><button className="d-project-card" key={p.id} onClick={()=>openProject(p.id)}><span className="d-project-card-icon" style={{color:p.color,background:`${p.color||'#8570cc'}15`}}>{p.icon||'✳'}</span><div><strong>{p.name}{p.is_private&&<LockKeyhole size={11}/>}</strong><p>{p.description||'A shared space for your ideas.'}</p><small>{liveBoards.filter(b=>b.project_id===p.id).length} boards</small></div><ChevronRight size={16}/></button>)}</div>}
            {view==='trash'&&trashedProjects.map(p=><div className="d-trash-project" key={p.id}><span className="d-project-card-icon" style={{color:p.color,background:`${p.color||'#8570cc'}15`}}>{p.icon||'✳'}</span><span><strong>{p.name}</strong><small>Project · {data.boards.filter(b=>b.project_id===p.id&&b.deleted_at).length} boards in Trash</small></span><button className="d-button" disabled={busy||p.role!=='owner'} onClick={()=>void perform('project.restore',{project_id:p.id},'Project restored')}><Undo2 size={14}/>Restore project</button></div>)}
            {view!=='projects'&&<div className={`d-board-container d-board-${layout}`}>{visibleBoards.map(board=><article key={board.id} className="d-board-card" draggable={editable(board.role)&&canMove(board)&&!board.deleted_at} onDragStart={e=>{e.dataTransfer.setData('application/x-canvaslab-board',board.id);e.dataTransfer.effectAllowed='move'}}><button className="d-board-preview" onClick={()=>board.deleted_at?showDialog({kind:'restore-board',board}):openBoard(board.id)} aria-label={board.deleted_at?`Restore ${board.name}`:`Open ${board.name}`}>{board.deleted_at?<div className="d-preview-empty"><Trash2 size={25}/><span>Board in Trash</span></div>:<BoardPreview board={board} userId={user.id}/>}</button><div className="d-board-info"><div className="d-board-title-row"><span className="d-file-icon"><File size={14}/></span><button className="d-board-title" onClick={()=>board.deleted_at?showDialog({kind:'restore-board',board}):openBoard(board.id)}>{board.name}</button>{favoriteSet.has(board.id)&&<Star className="d-favorite-star" size={13} fill="currentColor"/>}<div className="d-relative d-board-menu-wrap"><button className="d-icon-button" aria-label={`Actions for ${board.name}`} data-menu onClick={()=>setMenu(menu===board.id?'':board.id)}><Ellipsis size={18}/></button>{menu===board.id&&<div className="d-context-menu d-menu-right">{board.deleted_at?<button onClick={()=>showDialog({kind:'restore-board',board})}><Undo2 size={15}/>Restore board</button>:<><button onClick={()=>openBoard(board.id)}><ArrowUpRight size={15}/>Open board</button><button onClick={()=>{setMenu('');void perform('board.favorite',{board_id:board.id,value:!favoriteSet.has(board.id)},favoriteSet.has(board.id)?'Removed from favorites':'Added to favorites')}}><Star size={15}/>{favoriteSet.has(board.id)?'Remove favorite':'Add to favorites'}</button>{editable(board.role)&&<><hr/><button onClick={()=>showDialog({kind:'rename',board})}><Pencil size={15}/>Rename</button><button disabled={busy||!destinations.length} onClick={()=>duplicateBoard(board)}><Copy size={15}/>Duplicate</button>{canMove(board)&&<button onClick={()=>moveBoard(board)}><MoveRight size={15}/>Move to…</button>}<hr/><button className="d-danger" onClick={()=>showDialog({kind:'trash-board',board})}><Trash2 size={15}/>Move to Trash</button></>}</>}</div>}</div></div><p className="d-board-project">{data.projects.find(p=>p.id===board.project_id)?.name||board.project_name||'Shared with you'}</p><div className="d-board-bottom"><span className="d-owner-avatar" style={{background:board.created_by===user.id?user.color||'#ede1d7':'#e8e4f0'}}>{avatarLetters(board.owner_name||user.name)}</span><span>{board.owner_name||(board.created_by===user.id?'You':'Collaborator')}</span><span className="d-board-time">{relativeTime(board.updated_at||board.created_at)}</span></div></div></article>)}</div>}
            {((view==='projects'&&!shownProjects.length)||(view!=='projects'&&!visibleBoards.length&&!(view==='trash'&&trashedProjects.length)))&&<div className="d-empty"><div className="d-empty-art"><span/><span/><span/>{view==='trash'?<Trash2 size={29}/>:view==='favorites'?<Star size={30}/>:view==='shared'?<Users size={30}/>:view==='projects'?<FolderKanban size={30}/>:<File size={30}/>}</div><h3>{query?'No matching ideas just yet.':view==='trash'?'All clear here.':view==='favorites'?'Keep your best ideas close.':view==='recent'?'Your next idea starts here.':view==='shared'?'A little better, together.':view==='projects'?'Give your ideas a home.':'Your next big idea needs a little space.'}</h3><p>{query?'Try another name or a shorter search.':view==='trash'?'Deleted boards and projects will appear here.':view==='favorites'?'Star a board from its menu to find it here.':view==='recent'?'The boards you open will be waiting for you here.':view==='shared'?'Boards shared directly with you will appear here.':view==='projects'?'Create a project, then fill it with boards for your team.':'Start with a blank board, or let a template get you thinking.'}</p>{query?<button className="d-button" onClick={()=>setQuery('')}>Clear search</button>:['home','projects','recent'].includes(view)&&<button className="d-button d-button-primary" onClick={()=>view==='projects'?showDialog({kind:'project'}):newBoard()}><Plus size={15}/>{view==='projects'?'Create a project':'Create a board'}</button>}</div>}
          </section>
          {!projectId&&view==='home'&&<footer className="d-content-footer"><span>✳</span> An idea is a good place to start.</footer>}
        </>}
      </div>
    </main>
    <input hidden ref={importInput} type="file" accept=".canvaslab,application/json" aria-label="Import editable board file" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>18*1024*1024){setError('Editable board files must be 18 MB or smaller.');return}void file.text().then(text=>{const bundle=JSON.parse(text);if(!bundle||bundle.schemaVersion!==1||!Array.isArray(bundle.pages)||!Array.isArray(bundle.objects)||!Array.isArray(bundle.assets)||bundle.pages.length<1||bundle.pages.length>100||bundle.objects.length>15000||bundle.assets.length>500)throw new Error('This file is not a supported CanvasLab board.');setImportBundle(bundle);newBoard('import')}).catch(e=>setError(errorText(e)))}}/>{toast&&<div className="d-toast" role="status"><Check size={16}/>{toast}<button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={14}/></button></div>}
    {dialog&&<DashboardDialog importBundle={importBundle} key={dialog.kind+('id' in dialog?dialog.id:'board' in dialog?dialog.board.id:'project' in dialog?dialog.project?.id||'new':'workspace' in dialog?dialog.workspace?.id||'new':'template' in dialog?dialog.template:'')} dialog={dialog} workspace={workspace} currentProject={project} destinations={destinations} boards={data.boards} busy={busy} error={error} user={user} onClose={()=>{setDialog(null);setError('')}} perform={perform} closeAfter={closeAfter} onCreated={openBoard} onTemplate={newBoard}/>}
  </div>;
}

function DashboardDialog({importBundle,dialog,workspace,currentProject,destinations,boards,busy,error,user,onClose,perform,closeAfter,onCreated,onTemplate}:{importBundle?:EditableBundle;dialog:Dialog;workspace?:Workspace;currentProject?:Project;destinations:Project[];boards:Board[];busy:boolean;error:string;user:User;onClose:()=>void;perform:<T=unknown>(action:string,payload:Record<string,unknown>,message?:string)=>Promise<T|undefined>;closeAfter:(action:string,payload:Record<string,unknown>,message:string)=>Promise<void>;onCreated:(id:string)=>void;onTemplate:(template:string)=>void}) {
  const [name,setName]=useState(dialog.kind==='rename'?dialog.board.name:dialog.kind==='project'?dialog.project?.name||'':dialog.kind==='workspace'?dialog.workspace?.name||'':dialog.kind==='create-board'&&dialog.template==='import'?importBundle?.board?.name?.slice(0,160)||'Imported board':dialog.kind==='create-board'&&dialog.template!=='blank'?templates.find(t=>t.id===dialog.template)?.name||'Untitled board':'');
  const [description,setDescription]=useState(dialog.kind==='project'?dialog.project?.description||'':'');
  const [color,setColor]=useState(dialog.kind==='project'?dialog.project?.color||projectColors[0]:projectColors[0]);
  const [icon,setIcon]=useState(dialog.kind==='project'?dialog.project?.icon||'✳':'✳');
  const [isPrivate,setIsPrivate]=useState(dialog.kind==='project'?dialog.project?.is_private??true:true);
  const [destination,setDestination]=useState(dialog.kind==='move'?dialog.destination||destinations.find(p=>p.id!==dialog.board.project_id)?.id||'':currentProject&&editable(currentProject.role)?currentProject.id:destinations[0]?.id||'');
  const [members,setMembers]=useState<Member[]>([]);
  const [membersLoading,setMembersLoading]=useState(dialog.kind==='members');
  const [memberError,setMemberError]=useState('');
  const [email,setEmail]=useState('');
  const [role,setRole]=useState<Role>('editor');
  const [confirmAccess,setConfirmAccess]=useState(false);
  const loadMembers=useCallback(async()=>{if(dialog.kind!=='members')return;try{const result=await api<{members:Member[]}>(`${dialog.entity}.members`,{[`${dialog.entity}_id`]:dialog.id});setMembers(result.members);setMemberError('')}catch(cause){setMemberError(errorText(cause))}finally{setMembersLoading(false)}},[dialog]);
  useEffect(()=>{void loadMembers()},[loadMembers]);
  const title = dialog.kind==='create-board'?(dialog.template==='import'?'Import an editable board':'A new space for your ideas'):dialog.kind==='templates'?'Find your starting point':dialog.kind==='project'?(dialog.project?'Edit project':'Create a project'):dialog.kind==='workspace'?(dialog.workspace?'Workspace settings':'Create a workspace'):dialog.kind==='rename'?'Rename board':dialog.kind==='move'?'Move board to a project':dialog.kind==='trash-board'?'Move this board to Trash?':dialog.kind==='trash-project'?'Move this project to Trash?':dialog.kind==='restore-board'?'Restore your board':`People in ${dialog.name}`;
  async function submit(e:FormEvent) {e.preventDefault();
    if(dialog.kind==='create-board'&&dialog.template==='import'){const result=await perform<{board:Board}>('board.import',{project_id:destination,bundle:importBundle,name:name.trim()||'Imported board'});if(result){onClose();onCreated(result.board.id)}return}
    if(dialog.kind==='create-board'){const doc=makeTemplate(dialog.template);const initial_update=bytesToBase64(Y.encodeStateAsUpdate(doc));doc.destroy();const result=await perform<{board:Board}>('board.create',{project_id:destination,name:name.trim()||'Untitled board',initial_update});if(result){onClose();onCreated(result.board.id)}}
    if(dialog.kind==='project'){await closeAfter(dialog.project?'project.update':'project.create',{...(dialog.project?{project_id:dialog.project.id}:{workspace_id:workspace?.id}),name:name.trim(),description,color,icon,...(!dialog.project||dialog.project.role==='owner'?{is_private:isPrivate}:{})},dialog.project?'Project updated':'Project created')}
    if(dialog.kind==='workspace'){await closeAfter(dialog.workspace?'workspace.update':'workspace.create',{...(dialog.workspace?{workspace_id:dialog.workspace.id}:{}),name:name.trim()},dialog.workspace?'Workspace updated':'Workspace created')}
    if(dialog.kind==='rename')await closeAfter('board.update',{board_id:dialog.board.id,name:name.trim()},'Board renamed');
    if(dialog.kind==='move')await closeAfter('board.update',{board_id:dialog.board.id,project_id:destination,access_confirmed:confirmAccess},'Board moved. Its URL and content are unchanged.');
    if(dialog.kind==='trash-board')await closeAfter('board.trash',{board_id:dialog.board.id},'Board moved to Trash');
    if(dialog.kind==='trash-project')await closeAfter('project.trash',{project_id:dialog.project.id},'Project moved to Trash');
    if(dialog.kind==='restore-board')await closeAfter('board.restore',{board_id:dialog.board.id,...(destinations.some(p=>p.id===dialog.board.project_id)?{}:{project_id:destination})},'Board restored');
    if(dialog.kind==='members'){const result=await perform(`${dialog.entity}.member_set`,{[`${dialog.entity}_id`]:dialog.id,email,role},'Member access updated');if(result!==undefined){setEmail('');await loadMembers()}}
  }
  return <Modal title={title} onClose={onClose} wide={dialog.kind==='templates'}>
    {dialog.kind==='templates'?<div className="d-modal-body"><p className="d-dialog-intro">Ready-to-use canvases made of editable objects. Make each one your own.</p><div className="d-template-library"><button className="d-library-blank" onClick={()=>onTemplate('blank')}><Plus size={25}/><strong>Blank board</strong><span>Start with a clean canvas</span></button>{templates.map(template=><button key={template.id} className="d-library-template" onClick={()=>onTemplate(template.id)}><div style={{background:template.color}}><TemplatePreview type={template.id}/></div><strong>{template.name}</strong><span>{template.tag}</span></button>)}</div></div>:<form onSubmit={submit} className="d-dialog-form">
      <div className="d-modal-body">
        {dialog.kind==='create-board'&&<><div className="d-create-preview">{['blank','import'].includes(dialog.template)?<div className="d-blank-preview"><Plus size={27}/><span>{dialog.template==='import'?`${importBundle?.pages.length||0} pages · ${importBundle?.objects.length||0} editable objects`:'A fresh canvas, just for you.'}</span></div>:<><div style={{background:templates.find(t=>t.id===dialog.template)?.color}}><TemplatePreview type={dialog.template}/></div><span><LayoutTemplate size={14}/>{templates.find(t=>t.id===dialog.template)?.name} template</span></>}</div><label className="d-field">Board name<input autoFocus required maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="Give your idea a name"/></label></>}
        {(dialog.kind==='create-board'||dialog.kind==='move'||dialog.kind==='restore-board'&&!destinations.some(p=>p.id===dialog.board.project_id))&&<label className="d-field">{dialog.kind==='restore-board'?'Choose a new home — the original project is unavailable':'Project'}<select required value={destination} onChange={e=>{setDestination(e.target.value);setConfirmAccess(false)}}>{destinations.filter(p=>dialog.kind!=='move'||p.id!==dialog.board.project_id).map(p=><option value={p.id} key={p.id}>{p.icon||'✳'} {p.name}{p.is_private?' · Private':''}</option>)}</select>{!destinations.length&&<span className="d-field-help">You need an editable project to continue.</span>}</label>}
        {dialog.kind==='move'&&<><div className="d-access-notice"><Users size={19}/><div><strong>Moving a board can change who can access it.</strong><p>Access follows the destination project. Members of the new project may gain access, and members of the previous project may lose it. Direct board grants and share links remain active. The board’s content and URL stay the same.</p></div></div><label className="d-check-field"><input type="checkbox" required checked={confirmAccess} onChange={e=>setConfirmAccess(e.target.checked)}/>I understand that project access will change.</label></>}
        {(dialog.kind==='workspace'||dialog.kind==='project'||dialog.kind==='rename')&&<label className="d-field">{dialog.kind==='rename'?'Board':dialog.kind==='workspace'?'Workspace':'Project'} name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} maxLength={dialog.kind==='rename'?160:120} placeholder={dialog.kind==='project'?'e.g. Digital Product':dialog.kind==='workspace'?'e.g. Khalifah Team':'Board name'}/></label>}
        {dialog.kind==='project'&&<><label className="d-field">Description <span className="d-optional">Optional</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What will your team work on here?" rows={3} maxLength={2000}/></label><div className="d-field"><span>Make it your own</span><div className="d-project-options"><span className="d-project-card-icon" style={{color,background:`${color}18`}}>{icon}</span><div><div className="d-color-options">{projectColors.map(c=><button type="button" key={c} className={color===c?'active':''} style={{background:c}} aria-label={`Project color ${c}`} aria-pressed={color===c} onClick={()=>setColor(c)}>{color===c&&<Check size={12}/>}</button>)}</div><div className="d-icon-options">{projectIcons.map(i=><button type="button" key={i} className={icon===i?'active':''} aria-label={`Project icon ${i}`} aria-pressed={icon===i} onClick={()=>setIcon(i)}>{i}</button>)}</div></div></div></div><label className="d-privacy-option"><LockKeyhole size={19}/><span><strong>Private project</strong><small>Project members and workspace owners can access its boards.</small></span><input type="checkbox" disabled={!!dialog.project&&dialog.project.role!=='owner'} checked={isPrivate} onChange={e=>setIsPrivate(e.target.checked)}/></label></>}
        {dialog.kind==='trash-board'&&<p className="d-dialog-intro"><strong>{dialog.board.name}</strong> will move to Trash. People with access won’t be able to open or edit it. You can restore it later.</p>}
        {dialog.kind==='trash-project'&&<><p className="d-dialog-intro"><strong>{dialog.project.name}</strong> and <strong>{boards.filter(b=>b.project_id===dialog.project.id&&!b.deleted_at).length} active boards</strong> will move to Trash. Their content stays saved and editing will stop.</p><p className="d-field-help">Restoring this project brings back the boards moved with it. Boards already in Trash remain there.</p></>}
        {dialog.kind==='restore-board'&&<p className="d-dialog-intro"><strong>{dialog.board.name}</strong> will be available in its project again, with its saved content and the same URL.</p>}
        {dialog.kind==='members'&&<><p className="d-dialog-intro">{dialog.entity==='workspace'?'Workspace members can access shared projects. Private projects need a separate invitation.':'Private project access is limited to project members and workspace owners.'}</p>{membersLoading?<div className="d-member-loading"><LoaderCircle className="d-spin" size={18}/>Loading members…</div>:<div className="d-members-list">{members.map((member,i)=>{const person=member.user||member;const id=member.user_id||member.id;return <div className="d-member" key={id||i}><span className="d-user-avatar" style={{background:person.color||'#e5daef'}}>{avatarLetters(person.name||person.email||'Member')}</span><span><strong>{person.name||person.email||'Member'}{id===user.id?' (you)':''}</strong><small>{person.email}</small></span>{dialog.role==='owner'&&member.role!=='owner'?<select aria-label={`Role for ${person.name||person.email}`} value={member.role} onChange={async e=>{const result=await perform(`${dialog.entity}.member_set`,{[`${dialog.entity}_id`]:dialog.id,email:person.email,role:e.target.value},'Member access updated');if(result!==undefined)await loadMembers()}}><option value="editor">Editor</option><option value="commenter">Commenter</option><option value="viewer">Viewer</option><option value="remove">Remove access</option></select>:<span className="d-role-tag">{member.role}</span>}</div>})}</div>}{memberError&&<div className="d-error" role="alert">{memberError}</div>}{dialog.role==='owner'&&<><div className="d-invite-heading">Add someone to this {dialog.entity}</div><div className="d-invite-fields"><input type="email" required placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} aria-label="Member email address"/><select value={role} onChange={e=>setRole(e.target.value as Role)} aria-label="Member role"><option value="editor">Editor</option><option value="commenter">Commenter</option><option value="viewer">Viewer</option></select></div><p className="d-field-help">Use the email of an existing CanvasLab account. Access is granted immediately.</p></>}</>}
        {error&&<div className="d-error d-dialog-error" role="alert">{error}</div>}
      </div>
      <footer className="d-modal-footer"><button type="button" className="d-button" onClick={onClose}>{dialog.kind==='members'?'Done':'Cancel'}</button>{(dialog.kind!=='members'||dialog.role==='owner')&&<button className={`d-button ${dialog.kind.startsWith('trash')?'d-button-danger':'d-button-primary'}`} disabled={busy||(dialog.kind==='move'&&(!destination||!confirmAccess))||(dialog.kind==='create-board'&&!destination)}>{busy?<LoaderCircle className="d-spin" size={15}/>:dialog.kind.startsWith('trash')?<Trash2 size={14}/>:dialog.kind==='create-board'?<Plus size={15}/>:null}{dialog.kind==='create-board'?(dialog.template==='import'?'Import board':'Create board'):dialog.kind==='project'?(dialog.project?'Save changes':'Create project'):dialog.kind==='workspace'?(dialog.workspace?'Save changes':'Create workspace'):dialog.kind==='rename'?'Save name':dialog.kind==='move'?'Move board':dialog.kind.startsWith('trash')?'Move to Trash':dialog.kind==='restore-board'?'Restore board':'Grant access'}{dialog.kind==='create-board'&&<ArrowRight size={14}/>}</button>}</footer>
    </form>}
  </Modal>;
}
